-- liquibase formatted sql
-- changeset codified:createWordMatchesTables-20230623

CREATE TABLE WordMatchesBible (id INTEGER CONSTRAINT PK_WORDMATCHESBIBLE PRIMARY KEY AUTOINCREMENT NOT NULL, word TEXT NOT NULL, matches INTEGER DEFAULT 0);

CREATE TABLE WordMatchesDan (id INTEGER CONSTRAINT PK_WORDMATCHESDAN PRIMARY KEY AUTOINCREMENT NOT NULL, word TEXT NOT NULL, matches INTEGER DEFAULT 0);

CREATE TABLE WordMatchesDanRev (id INTEGER CONSTRAINT PK_WORDMATCHESDANREV PRIMARY KEY AUTOINCREMENT NOT NULL, word TEXT NOT NULL, matches INTEGER DEFAULT 0);

CREATE TABLE WordMatchesRev (id INTEGER CONSTRAINT PK_WORDMATCHESREV PRIMARY KEY AUTOINCREMENT NOT NULL, word TEXT NOT NULL, matches INTEGER DEFAULT 0);

CREATE UNIQUE INDEX IDX_WORD_WordMatchesBible ON WordMatchesBible(word);
CREATE INDEX IDX_MATCHES_WordMatchesBible ON WordMatchesBible(matches);

CREATE UNIQUE INDEX IDX_WORD_WordMatchesDanRev ON WordMatchesDanRev(word);
CREATE INDEX IDX_MATCHES_WordMatchesDanRev ON WordMatchesDanRev(matches);

CREATE UNIQUE INDEX IDX_WORD_WordMatchesDan ON WordMatchesDan(word);
CREATE INDEX IDX_MATCHES_WordMatchesDan ON WordMatchesDan(matches);

CREATE UNIQUE INDEX IDX_WORD_WordMatchesRev ON WordMatchesRev(word);
CREATE INDEX IDX_MATCHES_WordMatchesRev ON WordMatchesRev(matches);
